# fly.toml app configuration file generated for ben-litefs on 2023-06-13T11:18:26-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ben-litefs"
primary_region = "den"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[mount]
  source = "ben_litefs_db"
  destination = "/db"